use std::fs;
use std::path::Path;

use tauri_build::{AppManifest, Attributes};

/// 自动生成的 capability 文件名，路径相对于 src-tauri/。
///
/// tauri-build 默认扫描 `./capabilities/**/*` 加载所有 capability。
const GENERATED_CAPABILITY_PATH: &str = "capabilities/app-commands.generated.json";

/// Commands that must never be exposed to the Sunshine backend remote origin.
/// Their local window-scoped grants live in hand-written capability files.
const LOCAL_ONLY_COMMANDS: &[&str] = &["capture_screenshot"];

/// 允许 sunshine backend remote origin 调用 app commands 的 URL 列表。
///
/// sunshine GUI webview 启动后会跳转到 `https://localhost:47990` 等地址，
/// 在 tauri 视角下属于 remote origin（不在打包前端资源 frontendDist 范围内），
/// 必须显式声明 ACL 才能调用 custom commands（tauri 2.11+ PR #15266）。
const REMOTE_URLS: &[&str] = &[
    "http://localhost:*",
    "https://localhost:*",
    "http://127.0.0.1:*",
    "https://127.0.0.1:*",
];

/// 从 src/main.rs 的 `tauri::generate_handler![...]` 块中提取所有命令名。
///
/// 这样 AppManifest::commands 与生成的 capability 始终与 invoke_handler 同步，
/// 新增命令只需改 main.rs 一处，build.rs 自动同步 ACL。
fn extract_commands() -> Vec<String> {
    let src = fs::read_to_string("src/main.rs").expect("failed to read src/main.rs");
    let needle = "tauri::generate_handler![";
    let start = src
        .find(needle)
        .expect("could not find `tauri::generate_handler![` in src/main.rs");
    let after = &src[start + needle.len()..];
    let end = after
        .find(']')
        .expect("could not find closing `]` for generate_handler! block");
    let block = &after[..end];

    let mut cmds: Vec<String> = Vec::new();
    for line in block.lines() {
        let line = line
            .split("//")
            .next()
            .unwrap_or("")
            .trim()
            .trim_end_matches(',');
        if line.is_empty() {
            continue;
        }
        let name = line.rsplit("::").next().unwrap_or("").trim();
        if !name.is_empty() && name.chars().all(|c| c.is_alphanumeric() || c == '_') {
            cmds.push(name.to_string());
        }
    }

    assert!(
        !cmds.is_empty(),
        "extracted zero commands from generate_handler!"
    );
    cmds
}

/// 把命令名转成 ACL 权限名：install_vigem_driver -> allow-install-vigem-driver。
///
/// 与 tauri-utils acl::build::autogenerate_command_permissions 的 slug 规则一致。
/// 命令名前导 `_` 会被剥离避免出现 `allow--xxx` 这类双横线。
fn allow_id(command: &str) -> String {
    format!(
        "allow-{}",
        command.trim_start_matches('_').replace('_', "-")
    )
}

/// 生成 capability JSON 写入 capabilities 目录。
///
/// 该 capability 仅包含 app commands 的 allow- 权限并绑定 sunshine backend
/// remote URLs；窗口/插件/外部 URL 等由 `capabilities/default.json` 维护。
fn write_capability(commands: &[String]) {
    for local_only in LOCAL_ONLY_COMMANDS {
        assert!(
            commands.iter().any(|command| command == local_only),
            "LOCAL_ONLY_COMMANDS entry `{local_only}` was not found in generate_handler!"
        );
    }

    let permissions: Vec<String> = commands
        .iter()
        .filter(|command| !LOCAL_ONLY_COMMANDS.contains(&command.as_str()))
        .map(|command| allow_id(command))
        .collect();
    let permissions_lines = permissions
        .iter()
        .map(|p| format!("    {:?}", p))
        .collect::<Vec<_>>()
        .join(",\n");
    let remote_lines = REMOTE_URLS
        .iter()
        .map(|u| format!("      {:?}", u))
        .collect::<Vec<_>>()
        .join(",\n");

    let body = format!(
"{{
  \"$schema\": \"../gen/schemas/desktop-schema.json\",
  \"identifier\": \"app-commands\",
  \"description\": \"Auto-generated by build.rs - DO NOT EDIT. Allows sunshine GUI custom commands when invoked from sunshine backend remote origins.\",
  \"windows\": [\"*\"],
  \"webviews\": [\"*\"],
  \"remote\": {{
    \"urls\": [
{remote}
    ]
  }},
  \"permissions\": [
{perms}
  ]
}}
",
        remote = remote_lines,
        perms = permissions_lines,
    );

    let path = Path::new(GENERATED_CAPABILITY_PATH);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).expect("failed to create capabilities directory");
    }

    let needs_write = match fs::read_to_string(path) {
        Ok(existing) => existing != body,
        Err(_) => true,
    };
    if needs_write {
        fs::write(path, body).expect("failed to write generated capability");
    }
}

fn main() {
    // 告诉 Cargo 当这些文件变化时需要重新编译
    // 这样 include_str! 宏就能读取到最新版本的文件
    println!("cargo:rerun-if-changed=inject-script.js");
    println!("cargo:rerun-if-changed=inject-styles.css");
    println!("cargo:rerun-if-changed=error-404.html");
    // 命令清单从 main.rs 解析，main.rs 变化需重跑 build.rs
    println!("cargo:rerun-if-changed=src/main.rs");

    let commands = extract_commands();
    write_capability(&commands);

    // AppManifest::commands 需要 &'static [&'static str]，泄漏成静态生命周期
    let leaked: Vec<&'static str> = commands
        .into_iter()
        .map(|s| Box::leak(s.into_boxed_str()) as &'static str)
        .collect();
    let leaked: &'static [&'static str] = Box::leak(leaked.into_boxed_slice());

    tauri_build::try_build(Attributes::new().app_manifest(AppManifest::new().commands(leaked)))
        .expect("failed to run tauri-build");
}
